sudo: required

services:
  - docker

env:
  - GUMBOCY_PYTHON_VERSION=py27
  - GUMBOCY_PYTHON_VERSION=pypy

before_install:
  - docker ps
  - docker info
  - docker version
  - ./scripts/git-set-file-times
  - docker pull commonsearch/gumbocy
  - make docker_build

script:
  - make docker_test

notifications:
  irc: "chat.freenode.net#commonsearch"
