
# Use container-based infrastructure
# https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "2.7"

# https://github.com/commonsearch/gumbocy/issues/5
#  - "pypy"

env:
  - GUMBO_VERSION=0.10.1

install:
  - make gumbo_build
  - pip install -r requirements.txt

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - automake
      - gcc
      - curl

script:
  - make test

notifications:
  irc: "chat.freenode.net#commonsearch"
